### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by micwoj92** [tladudtn/TF2-Configs#2]
Hello, mastercomfig is licensed using MIT license which includes the following text:
`The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.`
That means that if you are redistributing it, you need to included mastercomfig's license. You can read the whole license here
https://github.com/mastercomfig/mastercomfig/blob/release/LICENSE.md

**Comment by tladudtn** [comment]
- [V] ADD MIT LICENSE FILE
